proxy:
  image: jwilder/nginx-proxy:latest
  ports:
    - "80:80"
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"

db:
  image: postgres:9.4.2 # Heroku PostgreSQL Version
  ports:
    - "5432:5432" # Bind host port 5432 to PostgreSQL port 5432
  volumes_from:
    - dbdata
  environment:
    LC_ALL: C.UTF-8
    POSTGRES_PASSWORD: HowCanYouGuess

dbdata:
  image: postgres:9.4.2
  command: /bin/echo PostgreSQL Data Container

redis:
  image: redis

cache:
  image: memcached

web:
  build: .
  command: bundle exec unicorn -E production -c config/unicorn.rb
  environment:
    SECRET_KEY_BASE: abcdefg
    VIRTUAL_HOST: beer.docker
    RAILS_ENV: production
  links:
    - db
    - redis
    - cache

worker:
  build: .
  command: bundle exec sidekiq -C config/sidekiq.yml
  environment:
    SECRET_KEY_BASE: abcdefg
    RAILS_ENV: production
  links:
    - db
    - redis
    - cache
