default: &default
  adapter: postgresql
  pool: 5
  username: postgres
  password: <%= ENV["DB_ENV_POSTGRES_PASSWORD"] %>
  host: <%= ENV["DB_PORT_5432_TCP_ADDR"] %>
  port: <%= ENV["DB_PORT_5432_TCP_PORT"] %>

development:
  <<: *default
  database: demeter_development

test:
  <<: *default
  database: demeter_test

production:
  <<: *default
  pool: 25
  database: demeter_production

staging:
  <<: *default
  database: demeter_staging
